logging {
  debug: off
  to_syslog: yes
}

nodelist {
  node {
    name: proxmox
    nodeid: 1
    quorum_votes: 1
    ring0_addr: 172.20.17.202
  }
  node {
    name: pve2
    nodeid: 2
    quorum_votes: 1
    ring0_addr: 172.20.17.203
  }
  node {
    name: pve3
    nodeid: 3
    quorum_votes: 1
    ring0_addr: 172.20.17.204
  }
}

quorum {
  provider: corosync_votequorum
}

totem {
  cluster_name: JASOC-Cluster
  config_version: 3
  interface {
    linknumber: 0
  }
  ip_version: ipv4-6
  link_mode: passive
  secauth: on
  version: 2
}

