#cloud-config
# ============================================================================
#  jamsec-redteam — Estación de auditoría / Red Team del SOC de JAMSEC
#  Debian 13 + herramientas de pentest.  SOC 10.20.10.50/24, gw 10.20.10.1
#  Alcanza al cliente Apex (172.20.17.230) a través de jamsec-fw (NAT).
# ============================================================================
hostname: jamsec-redteam
fqdn: jamsec-redteam.jamsec.cat
manage_etc_hosts: true

users:
  - name: jamsec
    groups: [sudo]
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: Jamsec2026!
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHJrzrkaIbwLspktR5Xg/s/nwWklhrQXUqp1vbZgWyYU admin@debian-server
ssh_pwauth: true

package_update: true
packages:
  - nmap
  - sqlmap
  - hydra
  - nikto
  - whatweb
  - dirb
  - netcat-openbsd
  - ftp
  - default-mysql-client
  - curl
  - wget
  - python3
  - jq
  - hping3
  - bind9-dnsutils
  - git
  - qemu-guest-agent

write_files:
  - path: /home/jamsec/objetivo.txt
    permissions: '0644'
    content: |
      OBJETIVO DE AUDITORÍA: Apex Gestoría
      Perímetro (WAN del cliente): 172.20.17.230
      Servicios publicados conocidos: 80/tcp (web), 2222/tcp (ssh), 21/tcp (ftp)
      Redes internas (tras pivote): DMZ 10.30.20.0/24, LAN 10.30.10.0/24

runcmd:
  - systemctl enable --now qemu-guest-agent
  - mkdir -p /home/jamsec/auditoria
  - chown -R jamsec:jamsec /home/jamsec

final_message: "jamsec-redteam listo tras $UPTIME segundos"
