#!/usr/sbin/nft -f
# Ruleset del firewall perimetral JAMSEC (jamsec-fw)
# Filtrado por SUBRED (independiente del nombre de interfaz).
flush ruleset

define NET_SOC = 10.20.10.0/24
define NET_DMZ = 10.20.20.0/24
define NET_SRV = 10.20.30.0/24
define NET_JAMSEC = 10.20.0.0/16
define WAN_IP = 172.20.17.211
define WEB_DMZ = 10.20.20.10

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        iif "lo" accept
        ct state established,related accept
        ct state invalid drop
        ip protocol icmp accept
        # Gestión SSH del firewall desde tránsito (WAN) y desde el SOC
        ip saddr 172.20.17.0/24 tcp dport 22 accept
        ip saddr $NET_SOC tcp dport 22 accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
        ct state established,related accept
        ct state invalid drop

        # SOC (analistas + SIEM): acceso completo a todas las zonas e internet
        ip saddr $NET_SOC accept

        # SRV (servicios internos): SOLO salida a internet, NO a otras zonas internas
        ip saddr $NET_SRV ip daddr != { $NET_SOC, $NET_DMZ } accept

        # DMZ: SOLO salida a internet (updates). NO puede ir a SRV ni SOC.
        ip saddr $NET_DMZ ip daddr != { $NET_SOC, $NET_SRV } accept

        # Internet/tránsito -> web pública en DMZ (tras DNAT): SOLO desde fuera
        # de la red JAMSEC (impide que SRV/otras zonas internas usen este atajo).
        ip saddr != $NET_JAMSEC ip daddr $WEB_DMZ tcp dport { 80, 443 } accept

        # Todo lo demás: DROP por política
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

table ip nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        # Publicación de la web corporativa: WAN:80/443 -> jamsec-web
        ip daddr $WAN_IP tcp dport 80 dnat to $WEB_DMZ:80
        ip daddr $WAN_IP tcp dport 443 dnat to $WEB_DMZ:443
    }
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        # NAT de las redes internas hacia internet
        ip saddr $NET_JAMSEC ip daddr != $NET_JAMSEC masquerade
    }
}
